xuperchain/docs

source/design_documents/xvm.rst, source/index.rst
=> fix grammar

source/advanced_usage/contract_accounts.rst
=> Add sample for acl addrs

source/advanced_usage/create_contracts.rst
docs for java native contracts
=> docs for java native contracts

.gitignore, requirements.txt, source/conf.py
https://sphinx-themes.org/sample-sites/renku-sphinx-theme/
=> RFC: Update theme to renku

Dockerfile
static file like *.css  is not watched  which require restart when static file changed in preview.
watch static files in order to auto sync when static file changes
=> watch static file change in preview mode

source/quickstart/quickstart.rst
=> 新增快速开始+基本操作

source/advanced_usage/parallel_chain.rst
=> add paraller chain and group doc

source/design_documents/regulatory.rst
=> fix identity contract url

source/development_manuals/contract-sdk.rst, source/development_manuals/dapp_development.rst
Add contract sdk documentation
=> Add contract sdk documentation

source/advanced_usage/contract_management.rst
=> Add contract manage

source/conf.py
add version to fix documentation titile disappearance problem
Please delete options that are not.
=> add version to fix documentation titile disappearance problem

source/_static/custom.css, source/_templates/breadcrumbs.html, source/tree.rst
=> edit breadcrumbs and custom.css

source/_static/custom.css, source/_templates/breadcrumbs.html, source/split/application.html, source/split/quicklyentrance.html, source/split/technologyintroduction.html
add 	custom.css edit
breadcrumbs.html edit
application.html link
quicklyentrance.html link
technologyintroduction.html link
=> add some links

source/split/technologyintroduction.html
add links in advanced_usage/performance_introduction.html of XuperIDE and XuperBench
=> link3 add IDEandBench links

source/_static/caption.js
edit function of /source/_static/caption.js
=> edit caption.js

source/_static/caption.js, source/_static/custom.css
edit caption.js anchor and custom.css .hov2
=> Anchor point

source/_static/custom.css, source/split/application.html
edit custom.css of application , ecology ul and application.html
=> application edit custom.css and application.html

source/_static/caption.js, source/_static/custom.css, source/_templates/layout.html
add custom.css .hide and caption.js function and layout.html .hide div
=> search add caption.js

source/_static/custom.css, source/split/community.html
edit link of join and none of .download
=> edit link of join and none of .download

source/_templates/layout.html
fix encoding error of xuper5 doc
=> fix encoding error of xuper5 doc

source/_static/custom.css, source/split/community.html
ediit css of version and css of community community.html of question
=> version and css of community

source/_templates/breadcrumbs.html
=> Comm2 edit breadcrumbs.html img

source/_templates/breadcrumbs.html
=> fix edit_on_github error

source/_templates/breadcrumbs.html, source/split/ecology.html, source/split/quicklyentrance.html
=> using relateive path

source/_static/custom.css
=> other-versions css

source/split/community.html, source/split/quicklyentrance.html
edit advanceduse.png and community ./_static/images/close_icon.png ./_static/images/wx.png
=> edit advanceduse.png and community img

source/split/ecology.html, source/split/technologyintroduction.html
=> add xuperscan to ecology

source/quickstart/quickstart.rst
add java dependency to quickstart as it usual confuses users
=> quickstart: Add java dependency in quickstart

requirements.txt
fix style error in versions older than v3.12
=> fix style error in old versions

source/advanced_usage/parallel_chain.rst
=> 纠正xfront配置中 xuper 参数缩进

source/advanced_usage/performance_introduction.rst
=> 切换到文档对应版本的分支

source/advanced_usage/authority_management.rst
=> authority: add contract method acl

source/advanced_usage/contract_management.rst
=> fix golang native not have fee

source/quickstart/quickstart.rst
=> 增加 checkout -b

source/development_manuals/xuper-sdk/xuper-sdk-js.rst
增加针对开放网络的一些配置： http 地址，开放网络地址，背书服务配置
=> 调整js sdk 文档

source/design_documents/smart_contract.rst, source/index.rst, source/tree.rst
=> add design doc for xuperbridge and xvm

source/advanced_usage/authority_management.rst
调整命令 xchain-cli  ------>  ./bin/xchain-cli
增加文档详细说明
=> authority_management:  using relative path  in command line

Makefile
=> fix doc build error as user id not match

source/_static/custom.css, source/development_manuals/sdk_development.rst, source/development_manuals/xuper-sdk/xuper-http.rst
=> 增加xuperchain http接口文档

source/development_manuals/xuper-sdk/xuper-sdk-java.rst
=> Update maven version 3

.github/workflows/ci.yml
=> fix ci.yaml

source/development_manuals/xuper-sdk/xuper-http.rst
update the xuper-http.rst, fix the param desc error for  "getaccountbyak" and "getaddresscontracts".
=> fix the http desc

source/advanced_usage/contract_management.rst, source/design_documents/smart_contract.rst
Fix typo for contract
- correct typo
- fix link
Previewed in local server
=> Fix typo for contract

source/xuperos/xuperos_go.rst, source/xuperos/xuperos_java.rst, source/xuperos/xuperos_js.rst
fix xuperos-go-sdk.html one link for gosdk doc
=> fix xuperos-go-sdk.html one link for gosdk doc

source/advanced_usage/multi_nodes.rst
=> fulfil the #260

source/contribution/pull_requests.rst
- 添加 PR 关闭 Issue 的说明
- 添加 PR 回复评审意见的约定
=> Add convention for PR and reply
